// <auto-generated />
using System;
using Awantura.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Awantura.Infrastructure.Migrations
{
    [DbContext(typeof(AwanturaAuthDbContext))]
    [Migration("20241231145903_Add Questions data")]
    partial class AddQuestionsdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameState")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BluePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GreenPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YellowPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isBluePlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isGreenPlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isYellowPlayerReady")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("PlayerGameScores");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<int>("PointsForCorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bddc9a14-160e-4d5b-81f4-40a2bec33baa"),
                            Answers = "Warszawa;Kraków;Wrocław;Gdańsk",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Które miasto jest stolicą Polski?"
                        },
                        new
                        {
                            Id = new Guid("f7e5939c-32f0-4f5b-85ce-6bfc77ff87f7"),
                            Answers = "Europa;Azja;Afryka;Ameryka Południowa",
                            Category = 0,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który kontynent jest największy pod względem powierzchni?"
                        },
                        new
                        {
                            Id = new Guid("496b5864-aa3e-42ac-a237-ca7e7f01fc58"),
                            Answers = "K2;Mont Blanc;Mount Everest;Kilimandżaro",
                            Category = 0,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się najwyższy szczyt na Ziemi?"
                        },
                        new
                        {
                            Id = new Guid("bc04d412-0503-486f-84ae-f6078bc32dea"),
                            Answers = "Saturn;Uran;Neptun;Jowisz",
                            Category = 1,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Która planeta w Układzie Słonecznym jest największa?"
                        },
                        new
                        {
                            Id = new Guid("b4af2ab9-9d2e-464a-83ea-cd846b16fed6"),
                            Answers = "Droga Mleczna;Andromeda;Karłowata Galaktyka Strzelca;Wielka Mgławica",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się galaktyka, w której znajduje się Ziemia?"
                        },
                        new
                        {
                            Id = new Guid("941fa5ca-34e9-4a2f-9cc6-36d51d0847f0"),
                            Answers = "Wenus;Merkury;Mars;Ziemia",
                            Category = 1,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Która planeta jest najbliżej Słońca?"
                        },
                        new
                        {
                            Id = new Guid("c9ced94a-ddea-4fe5-be5f-c339b5e64006"),
                            Answers = "Oddychanie komórkowe;Fermentacja;Fotosynteza;Glukoneogeneza",
                            Category = 2,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jak nazywa się proces, w którym rośliny przekształcają światło słoneczne w energię?"
                        },
                        new
                        {
                            Id = new Guid("5add4748-11dd-45c0-9899-0f24c88d6e42"),
                            Answers = "Wątroba;Płuca;Mózg;Serce",
                            Category = 2,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Który organ w ludzkim ciele odpowiada za pompowanie krwi?"
                        },
                        new
                        {
                            Id = new Guid("87f0da7e-4d78-42c0-b918-99aabb1f8d3f"),
                            Answers = "Płetwal błękitny;Słoń;Rekin wielorybi;Żyrafa",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jakie zwierzę jest największe na świecie?"
                        },
                        new
                        {
                            Id = new Guid("164b3c0a-7065-4501-9577-6432e169eb0d"),
                            Answers = "Hel;Wodór;Azot;Tlen",
                            Category = 3,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który pierwiastek ma symbol H?"
                        },
                        new
                        {
                            Id = new Guid("1ab333f2-175d-4fe9-b287-45c7a13ba5c0"),
                            Answers = "Kwas siarkowy;Kwas fosforowy;Kwas octowy;Kwas solny",
                            Category = 3,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Który kwas jest składnikiem octu?"
                        },
                        new
                        {
                            Id = new Guid("a3ad6a35-3e4c-4d7b-a3fb-d7c1a8110f97"),
                            Answers = "Krzem;Cynk;Srebro;Węgiel",
                            Category = 3,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który pierwiastek jest podstawowym składnikiem diamentu?"
                        },
                        new
                        {
                            Id = new Guid("d6ed2e6d-d205-4a48-819c-2e91883f4ecb"),
                            Answers = "Andrzej Wajda;Roman Polański;Krzysztof Kieślowski;Agnieszka Holland",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Kto jest reżyserem filmu 'Człowiek z marmuru'?"
                        },
                        new
                        {
                            Id = new Guid("deeea496-fb0f-4182-add7-5b93c55cea25"),
                            Answers = "Cicha noc;Ida;Katyń;Pan Tadeusz",
                            Category = 4,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który polski film zdobył Oscara?"
                        },
                        new
                        {
                            Id = new Guid("b9556a01-0995-477b-aba8-fde3817a64ff"),
                            Answers = "Andrzej Wajda;Agnieszka Holland;Krzysztof Kieślowski;Jerzy Hoffman",
                            Category = 4,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Kto jest twórcą trylogii filmowej 'Dekalog'?"
                        },
                        new
                        {
                            Id = new Guid("0dfbfb31-83c9-44e8-bfdd-11f2562ae825"),
                            Answers = "Niemcy;Brazylia;Argentyna;Francja",
                            Category = 5,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Która reprezentacja wygrała Mistrzostwa Świata w Piłce Nożnej w 2018 roku?"
                        },
                        new
                        {
                            Id = new Guid("2645075b-f485-4e1c-80f5-fdfafba0566c"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Jak nazywa się polski piłkarz, który zdobył Złotą Piłkę?"
                        },
                        new
                        {
                            Id = new Guid("c1add7e4-6aef-4973-82e8-70fa7723d9f5"),
                            Answers = "FC Barcelona;Real Madryt;AC Milan;Bayern Monachium",
                            Category = 5,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który klub piłkarski wygrał najwięcej Lig Mistrzów?"
                        },
                        new
                        {
                            Id = new Guid("ad1372d0-1799-4a8b-a1a7-a52982a980b8"),
                            Answers = "Karaś;Leszcz;Pstrąg;Karp",
                            Category = 6,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Która ryba jest typowym drapieżnikiem?"
                        },
                        new
                        {
                            Id = new Guid("818698a6-596e-40ad-87e0-dfee10c3fd48"),
                            Answers = "Wędkarstwo gruntowe;Metoda odległościowa;Trolling;Spinning",
                            Category = 6,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się metoda połowu na sztuczną przynętę?"
                        },
                        new
                        {
                            Id = new Guid("9bf78086-cef9-4c6e-8c37-5faf774ded9a"),
                            Answers = "Waga wędkarska;Podbierak;Wędka;Kołowrotek",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się przyrząd do ważenia złowionych ryb?"
                        },
                        new
                        {
                            Id = new Guid("621b1012-b631-46ba-93b2-d992f31aaff2"),
                            Answers = "Lech Wałęsa;Andrzej Duda;Aleksander Kwaśniewski;Donald Tusk",
                            Category = 7,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Kto jest prezydentem Polski w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("d3385bb2-7ab8-4753-b5db-16c927660ecf"),
                            Answers = "Chiny;Indie;Stany Zjednoczone;Rosja",
                            Category = 7,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Które państwo posiada najwięcej miejsc w ONZ?"
                        },
                        new
                        {
                            Id = new Guid("54bad5c9-c23c-4785-b26c-6a3729490067"),
                            Answers = "Paryż;Berlin;Strasburg;Bruksela",
                            Category = 7,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się główna siedziba Parlamentu Europejskiego?"
                        },
                        new
                        {
                            Id = new Guid("cb75dc26-5386-4251-930c-2d2315aca70f"),
                            Answers = "Śniardwy;Mamry;Hańcza;Niegocin",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jakie jest największe jezioro w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("6777b191-5cd7-4fbf-96b6-eb089117996f"),
                            Answers = "Niemcy;Czechy;Słowacja;Litwa",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który kraj graniczy z Polską na zachodzie?"
                        },
                        new
                        {
                            Id = new Guid("a8388b5a-322f-4f82-a941-3adc5ff42664"),
                            Answers = "Tatry;Sudety;Karpaty;Bieszczady",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Które pasmo górskie znajduje się na południu Polski?"
                        },
                        new
                        {
                            Id = new Guid("8746e07c-69dc-4131-b74c-a770795723ce"),
                            Answers = "Merkury;Mars;Wenus;Pluton",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się najmniejsza planeta w Układzie Słonecznym?"
                        },
                        new
                        {
                            Id = new Guid("4f0efa39-8682-4c54-8e24-062da22ff42a"),
                            Answers = "Saturn;Jowisz;Neptun;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Która planeta jest znana z systemu pierścieni?"
                        },
                        new
                        {
                            Id = new Guid("9f4f71bd-bbcd-4f74-a32a-6491fea718bd"),
                            Answers = "Księżyc;Mars;Wenus;Merkury",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Jak nazywa się najbliższy Ziemi obiekt astronomiczny?"
                        },
                        new
                        {
                            Id = new Guid("81499291-c646-4e41-93c9-afdb6471d035"),
                            Answers = "Lew;Tygrys;Słoń;Goryl",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jakie zwierzę jest nazywane królem dżungli?"
                        },
                        new
                        {
                            Id = new Guid("8d7c6f75-a5a2-4c8b-b340-dff472e0a7c5"),
                            Answers = "Botanika;Zoologia;Ekologia;Genetyka",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się nauka o roślinach?"
                        },
                        new
                        {
                            Id = new Guid("cf6dfdbd-f3d4-4ac4-9e85-d03270d48372"),
                            Answers = "Słuch;Wzrok;Dotyk;Smak",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który zmysł odpowiada za wykrywanie dźwięków?"
                        },
                        new
                        {
                            Id = new Guid("b203decb-a821-4739-a095-9a4b89f378ca"),
                            Answers = "Au;Ag;Fe;Cu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się symbol chemiczny dla złota?"
                        },
                        new
                        {
                            Id = new Guid("c2ed00cb-bf2d-444a-9c68-c73a069635e9"),
                            Answers = "Tlen;Wodór;Azot;Hel",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który pierwiastek ma symbol O?"
                        },
                        new
                        {
                            Id = new Guid("7b82a06f-e607-45d4-80ff-6d1f4e3a8643"),
                            Answers = "Woda;Tlenek wodoru;Para wodna;Sól",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Co to jest H2O?"
                        },
                        new
                        {
                            Id = new Guid("a9686176-a9da-4407-a5b2-d87a49c377e1"),
                            Answers = "Jerzy Radziwiłowicz;Zbigniew Cybulski;Daniel Olbrychski;Andrzej Seweryn",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Kto zagrał główną rolę w filmie 'Człowiek z żelaza'?"
                        },
                        new
                        {
                            Id = new Guid("0068fa56-c1ab-4d57-96e5-96dc950057ba"),
                            Answers = "Jerzy Antczak;Andrzej Wajda;Agnieszka Holland;Krzysztof Zanussi",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Który polski reżyser stworzył film 'Noce i dnie'?"
                        },
                        new
                        {
                            Id = new Guid("d0a6c34f-d246-48bb-80c6-c34b29524a7c"),
                            Answers = "Adrien Brody;Roman Polański;Janusz Gajos;Bogusław Linda",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Który polski aktor zdobył Oscara za rolę w filmie 'Pianista'?"
                        },
                        new
                        {
                            Id = new Guid("c76f55a5-10ec-47fc-819c-1e5db6f065f3"),
                            Answers = "Brazylia;Niemcy;Włochy;Argentyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Która drużyna zdobyła najwięcej tytułów Mistrza Świata w piłce nożnej?"
                        },
                        new
                        {
                            Id = new Guid("aba08d72-fc18-422b-b905-542680bb34a9"),
                            Answers = "Lionel Messi;Cristiano Ronaldo;Johan Cruyff;Michel Platini",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Kto jest rekordzistą pod względem liczby zdobytych Złotych Piłek?"
                        },
                        new
                        {
                            Id = new Guid("f2d5a14e-f9b6-456b-a595-a0eadeb8aa85"),
                            Answers = "PGE Narodowy;Stadion Śląski;Stadion Legii;Arena Gdańsk",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się stadion narodowy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("9a14f569-3df1-4a99-ae0c-05d5eb145568"),
                            Answers = "Karp;Dorsz;Halibut;Łosoś",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Który gatunek ryb jest typowo uznawany za rybę słodkowodną?"
                        },
                        new
                        {
                            Id = new Guid("e5d314e8-2107-4df2-af51-f0f497fc94bc"),
                            Answers = "Kołowrotek;Wędzisko;Haczyk;Podbierak",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Jak nazywa się urządzenie do nawijania żyłki?"
                        },
                        new
                        {
                            Id = new Guid("a8162970-74c5-4c92-a4ab-f159a0573512"),
                            Answers = "Wędkarstwo gruntowe;Spinning;Trolling;Fly fishing",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się metoda łowienia ryb z brzegu?"
                        },
                        new
                        {
                            Id = new Guid("efc22779-45e4-464f-99f3-50d55fd7b910"),
                            Answers = "Sejm;Senat;Trybunał Konstytucyjny;Rada Ministrów",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się główny organ ustawodawczy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("2fc0da5b-e294-4af6-9471-e3065b681fac"),
                            Answers = "Wielka Brytania;Francja;Niemcy;Włochy",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który kraj opuścił Unię Europejską w 2020 roku?"
                        },
                        new
                        {
                            Id = new Guid("9bf55960-1c22-4f34-96bf-87d02b5ee631"),
                            Answers = "Konstytucja 3 maja;Konstytucja kwietniowa;Konstytucja marcowa;Konstytucja sierpniowa",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się polska konstytucja z 1791 roku?"
                        },
                        new
                        {
                            Id = new Guid("5758a086-88ba-4aa4-9782-5cb632520eee"),
                            Answers = "Kilimandżaro;Mount Kenya;Ruwenzori;Atlas",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Jak nazywa się najwyższy szczyt Afryki?"
                        },
                        new
                        {
                            Id = new Guid("3068df39-02cd-4987-b3f0-72d60cd85df9"),
                            Answers = "Morze Martwe;Morze Śródziemne;Morze Bałtyckie;Morze Kaspijskie",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Które morze jest nazywane najbardziej zasolonym?"
                        },
                        new
                        {
                            Id = new Guid("e6a4b266-f710-4623-aabe-3955184d750f"),
                            Answers = "Berlin;Monachium;Frankfurt;Hamburg",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jakie miasto jest stolicą Niemiec?"
                        },
                        new
                        {
                            Id = new Guid("e34e41dd-7ea9-42e9-98b3-de964d7e59e4"),
                            Answers = "Jowisz;Saturn;Mars;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Która planeta Układu Słonecznego ma największą liczbę księżyców?"
                        },
                        new
                        {
                            Id = new Guid("69aa3302-369d-4cae-b1d1-5ef5fbd7c8f1"),
                            Answers = "Eksplozja gwiazdy;Rodzaj galaktyki;Typ planety;Czarna dziura",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Co to jest supernowa?"
                        },
                        new
                        {
                            Id = new Guid("4603ee74-570d-46b2-bb41-e003b0c2de86"),
                            Answers = "Wenus;Jowisz;Mars;Syriusz",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Jak nazywa się drugi pod względem jasności obiekt na nocnym niebie po Księżycu?"
                        },
                        new
                        {
                            Id = new Guid("f3f2bf6b-43c6-481e-943a-64577f88a04f"),
                            Answers = "Gepard;Antylopa;Lew;Królik",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Które zwierzę jest najszybsze na lądzie?"
                        },
                        new
                        {
                            Id = new Guid("4b3529f9-9ce7-4183-bc8e-41efe07825af"),
                            Answers = "Metamorfoza;Adaptacja;Fotosynteza;Regeneracja",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się proces, w którym zwierzęta przechodzą zmiany w wyglądzie w czasie rozwoju?"
                        },
                        new
                        {
                            Id = new Guid("6f01740e-8dbf-4863-81a2-f8e134ea3867"),
                            Answers = "Komórki;Tkanki;Narządy;Organizmy",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Jakie są podstawowe jednostki budulcowe organizmów żywych?"
                        },
                        new
                        {
                            Id = new Guid("4b814e1b-89c0-4f20-bbaa-0fe2acd7072d"),
                            Answers = "Węgiel;Wapń;Cynk;Chrom",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który pierwiastek ma symbol C?"
                        },
                        new
                        {
                            Id = new Guid("3d8af246-d5a9-4268-8413-10ab864e2ce6"),
                            Answers = "Chlorek sodu;Wodorowęglan sodu;Siarczan sodu;Azotan sodu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który związek chemiczny jest głównym składnikiem soli kuchennej?"
                        },
                        new
                        {
                            Id = new Guid("908917e6-a421-4993-b532-66a0b38cb439"),
                            Answers = "Powietrze;Woda z piaskiem;Olej i woda;Puder do twarzy",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Która mieszanina jest jednorodna?"
                        },
                        new
                        {
                            Id = new Guid("b94d69d2-57b0-494f-ac92-1c045b1fdece"),
                            Answers = "Marek Piwowski;Andrzej Wajda;Roman Polański;Krzysztof Kieślowski",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Kto jest reżyserem filmu 'Rejs'?"
                        },
                        new
                        {
                            Id = new Guid("8ba65ad7-0bb9-4ddd-9076-049b7018fb5f"),
                            Answers = "Olaf Lubaszenko;Bogusław Linda;Zbigniew Cybulski;Jan Nowicki",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Który polski aktor grał w filmie 'Krótki film o miłości'?"
                        },
                        new
                        {
                            Id = new Guid("9ceba7f5-890d-4538-a838-acf6d13365ac"),
                            Answers = "Człowiek z żelaza;Dekalog;Ida;Pokot",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który film polskiego reżysera zdobył Złotą Palmę w Cannes?"
                        },
                        new
                        {
                            Id = new Guid("6512863f-85fd-4daf-b0ce-27295e37230a"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który polski piłkarz grał w Bayernie Monachium?"
                        },
                        new
                        {
                            Id = new Guid("a32f8408-f2d8-440b-aadc-3e9cd56908f1"),
                            Answers = "Adam Nawałka;Jerzy Brzęczek;Paulo Sousa;Franciszek Smuda",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Kto był trenerem reprezentacji Polski w piłce nożnej na Euro 2016?"
                        },
                        new
                        {
                            Id = new Guid("8b0aac57-09bc-46dc-9f8d-77c56749befb"),
                            Answers = "Ronaldo Nazário;Lionel Messi;Diego Maradona;Cristiano Ronaldo",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Który piłkarz jest znany jako 'El Fenomeno'?"
                        },
                        new
                        {
                            Id = new Guid("061b66f8-3cb2-43b2-8ec0-fde7bff8aec8"),
                            Answers = "Fly fishing;Trolling;Spinning;Wędkarstwo gruntowe",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który rodzaj wędkowania wymaga sztucznej muchy?"
                        },
                        new
                        {
                            Id = new Guid("4130f9ea-0aee-4b15-8d6c-394d9e0f5e91"),
                            Answers = "Włókno węglowe;Drewno;Stal;Aluminium",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jakie jest najczęściej używane tworzywo do produkcji wędek?"
                        },
                        new
                        {
                            Id = new Guid("efffffeb-5182-49ec-bf9d-793e615443af"),
                            Answers = "Ryba ciągnie przynętę;Ryba pływa obok;Wędka jest zanurzona;Przynęta jest zmieniana",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Co oznacza termin 'brać' w wędkarstwie?"
                        },
                        new
                        {
                            Id = new Guid("1e9d83c4-28f2-4a5b-ace1-ea141b8ec7ea"),
                            Answers = "Charles Michel;Ursula von der Leyen;Donald Tusk;Angela Merkel",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Kto jest przewodniczącym Rady Europejskiej w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("49e0f4e4-ecb9-4c7a-8ac2-50d35021fd10"),
                            Answers = "Traktat Lizboński;Traktat z Maastricht;Traktat Rzymski;Traktat Amsterdamski",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który dokument jest podstawą prawną Unii Europejskiej?"
                        },
                        new
                        {
                            Id = new Guid("b7265ea1-e953-455f-a7ca-d462f12f6607"),
                            Answers = "Mateusz Morawiecki;Donald Tusk;Jarosław Kaczyński;Beata Szydło",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się premier Polski w 2024 roku?"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            ConcurrencyStamp = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "98063297-e6e0-4b99-a132-1e79147ce720",
                            ConcurrencyStamp = "98063297-e6e0-4b99-a132-1e79147ce720",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithOne("GameParticipants")
                        .HasForeignKey("Awantura.Domain.Entities.GameParticipants", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithMany("PlayerScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameParticipants")
                        .IsRequired();

                    b.Navigation("PlayerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
