// <auto-generated />
using System;
using Awantura.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Awantura.Infrastructure.Migrations
{
    [DbContext(typeof(AwanturaAuthDbContext))]
    [Migration("20250105103701_Add Pool and Balance fields for bidding purposes")]
    partial class AddPoolandBalancefieldsforbiddingpurposes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameState")
                        .HasColumnType("int");

                    b.Property<int>("Pool")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BluePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GreenPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YellowPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isBluePlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isGreenPlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isYellowPlayerReady")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("PlayerGameScores");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<int>("PointsForCorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82d2b0c1-63bf-418d-8d56-45769a5b44c2"),
                            Answers = "Warszawa;Kraków;Wrocław;Gdańsk",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Które miasto jest stolicą Polski?"
                        },
                        new
                        {
                            Id = new Guid("ed9c6832-6dd3-480d-a8b3-0320bbd8cc44"),
                            Answers = "Europa;Azja;Afryka;Ameryka Południowa",
                            Category = 0,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który kontynent jest największy pod względem powierzchni?"
                        },
                        new
                        {
                            Id = new Guid("8ab9c90d-018c-4691-b039-a7e44d32fda8"),
                            Answers = "K2;Mont Blanc;Mount Everest;Kilimandżaro",
                            Category = 0,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Jak nazywa się najwyższy szczyt na Ziemi?"
                        },
                        new
                        {
                            Id = new Guid("de59ae24-559b-49d3-ae54-69cc3e1d0bc8"),
                            Answers = "Saturn;Uran;Neptun;Jowisz",
                            Category = 1,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Która planeta w Układzie Słonecznym jest największa?"
                        },
                        new
                        {
                            Id = new Guid("7f0d1b7c-f690-4117-b3a3-deab2791fb5a"),
                            Answers = "Droga Mleczna;Andromeda;Karłowata Galaktyka Strzelca;Wielka Mgławica",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jak nazywa się galaktyka, w której znajduje się Ziemia?"
                        },
                        new
                        {
                            Id = new Guid("9f9af776-51b0-4af6-899d-5f4375aa8e06"),
                            Answers = "Wenus;Merkury;Mars;Ziemia",
                            Category = 1,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Która planeta jest najbliżej Słońca?"
                        },
                        new
                        {
                            Id = new Guid("e2203867-2147-43c4-9340-8bf8639d970f"),
                            Answers = "Oddychanie komórkowe;Fermentacja;Fotosynteza;Glukoneogeneza",
                            Category = 2,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się proces, w którym rośliny przekształcają światło słoneczne w energię?"
                        },
                        new
                        {
                            Id = new Guid("27839f82-5a1c-4a0b-ae0b-94ba38995622"),
                            Answers = "Wątroba;Płuca;Mózg;Serce",
                            Category = 2,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który organ w ludzkim ciele odpowiada za pompowanie krwi?"
                        },
                        new
                        {
                            Id = new Guid("04cd4e5c-5fbe-44a9-a169-5632ef9352b7"),
                            Answers = "Płetwal błękitny;Słoń;Rekin wielorybi;Żyrafa",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Jakie zwierzę jest największe na świecie?"
                        },
                        new
                        {
                            Id = new Guid("39c6ac24-7625-4c8b-9923-3d1306260fa8"),
                            Answers = "Hel;Wodór;Azot;Tlen",
                            Category = 3,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który pierwiastek ma symbol H?"
                        },
                        new
                        {
                            Id = new Guid("6799563f-db71-4b0f-9769-360a2286d71c"),
                            Answers = "Kwas siarkowy;Kwas fosforowy;Kwas octowy;Kwas solny",
                            Category = 3,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który kwas jest składnikiem octu?"
                        },
                        new
                        {
                            Id = new Guid("08aea720-5e49-45ef-80a7-8b1c1151ac33"),
                            Answers = "Krzem;Cynk;Srebro;Węgiel",
                            Category = 3,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który pierwiastek jest podstawowym składnikiem diamentu?"
                        },
                        new
                        {
                            Id = new Guid("5203ab6a-9519-4eed-80b2-b9ca311011ce"),
                            Answers = "Andrzej Wajda;Roman Polański;Krzysztof Kieślowski;Agnieszka Holland",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Kto jest reżyserem filmu 'Człowiek z marmuru'?"
                        },
                        new
                        {
                            Id = new Guid("27d3c4c5-a0ae-472e-b3e5-d1dbed620ed1"),
                            Answers = "Cicha noc;Ida;Katyń;Pan Tadeusz",
                            Category = 4,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który polski film zdobył Oscara?"
                        },
                        new
                        {
                            Id = new Guid("8bb957e7-663b-409f-9f2c-481e270c6846"),
                            Answers = "Andrzej Wajda;Agnieszka Holland;Krzysztof Kieślowski;Jerzy Hoffman",
                            Category = 4,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Kto jest twórcą trylogii filmowej 'Dekalog'?"
                        },
                        new
                        {
                            Id = new Guid("952178af-b043-42c0-9d45-ae5f12cbc3bd"),
                            Answers = "Niemcy;Brazylia;Argentyna;Francja",
                            Category = 5,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Która reprezentacja wygrała Mistrzostwa Świata w Piłce Nożnej w 2018 roku?"
                        },
                        new
                        {
                            Id = new Guid("f88e61f7-ccb8-4a64-bbff-6d90c3a912d6"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się polski piłkarz, który zdobył Złotą Piłkę?"
                        },
                        new
                        {
                            Id = new Guid("9943bc01-3190-438f-8238-a025fcffa5d3"),
                            Answers = "FC Barcelona;Real Madryt;AC Milan;Bayern Monachium",
                            Category = 5,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który klub piłkarski wygrał najwięcej Lig Mistrzów?"
                        },
                        new
                        {
                            Id = new Guid("dd0d002c-72b1-4878-a834-08ff764ac168"),
                            Answers = "Karaś;Leszcz;Pstrąg;Karp",
                            Category = 6,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Która ryba jest typowym drapieżnikiem?"
                        },
                        new
                        {
                            Id = new Guid("98734851-d654-4f92-8f2c-e674bbc1f818"),
                            Answers = "Wędkarstwo gruntowe;Metoda odległościowa;Trolling;Spinning",
                            Category = 6,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się metoda połowu na sztuczną przynętę?"
                        },
                        new
                        {
                            Id = new Guid("a5f3b8f0-82d4-4a4f-a221-e4e8eb59598c"),
                            Answers = "Waga wędkarska;Podbierak;Wędka;Kołowrotek",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jak nazywa się przyrząd do ważenia złowionych ryb?"
                        },
                        new
                        {
                            Id = new Guid("49930495-1dc0-4436-8fe7-6ba80a8cbc71"),
                            Answers = "Lech Wałęsa;Andrzej Duda;Aleksander Kwaśniewski;Donald Tusk",
                            Category = 7,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Kto jest prezydentem Polski w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("67374f65-3a29-44cd-91df-b3a11b3f6ef4"),
                            Answers = "Chiny;Indie;Stany Zjednoczone;Rosja",
                            Category = 7,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Które państwo posiada najwięcej miejsc w ONZ?"
                        },
                        new
                        {
                            Id = new Guid("c6d0305f-47d6-4b1c-872d-c75e18878404"),
                            Answers = "Paryż;Berlin;Strasburg;Bruksela",
                            Category = 7,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Jak nazywa się główna siedziba Parlamentu Europejskiego?"
                        },
                        new
                        {
                            Id = new Guid("e56aa46f-84ef-499b-ba21-8d49d8c54bdf"),
                            Answers = "Śniardwy;Mamry;Hańcza;Niegocin",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jakie jest największe jezioro w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("608af0dd-3317-4b04-aeb5-847671b9362e"),
                            Answers = "Niemcy;Czechy;Słowacja;Litwa",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który kraj graniczy z Polską na zachodzie?"
                        },
                        new
                        {
                            Id = new Guid("e0b8c43a-ca77-4222-b67a-f95b04cfd2fc"),
                            Answers = "Tatry;Sudety;Karpaty;Bieszczady",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Które pasmo górskie znajduje się na południu Polski?"
                        },
                        new
                        {
                            Id = new Guid("ef9d290b-4044-4e4b-8172-94993286f07f"),
                            Answers = "Merkury;Mars;Wenus;Pluton",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Jak nazywa się najmniejsza planeta w Układzie Słonecznym?"
                        },
                        new
                        {
                            Id = new Guid("2fa0aaad-1415-4e69-9df5-fcb04474b9f0"),
                            Answers = "Saturn;Jowisz;Neptun;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Która planeta jest znana z systemu pierścieni?"
                        },
                        new
                        {
                            Id = new Guid("f1030bfa-20d3-4a17-af6f-3b2a1f91cb07"),
                            Answers = "Księżyc;Mars;Wenus;Merkury",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jak nazywa się najbliższy Ziemi obiekt astronomiczny?"
                        },
                        new
                        {
                            Id = new Guid("cd003633-511e-42e0-a174-eb7db85127e4"),
                            Answers = "Lew;Tygrys;Słoń;Goryl",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jakie zwierzę jest nazywane królem dżungli?"
                        },
                        new
                        {
                            Id = new Guid("a315c886-ac7e-42ba-b4eb-5cba41f347d8"),
                            Answers = "Botanika;Zoologia;Ekologia;Genetyka",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jak nazywa się nauka o roślinach?"
                        },
                        new
                        {
                            Id = new Guid("e409e64a-61aa-42eb-ba3a-cb5bc999199e"),
                            Answers = "Słuch;Wzrok;Dotyk;Smak",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który zmysł odpowiada za wykrywanie dźwięków?"
                        },
                        new
                        {
                            Id = new Guid("fa270376-074f-43f7-ac4b-2567a3e0c421"),
                            Answers = "Au;Ag;Fe;Cu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się symbol chemiczny dla złota?"
                        },
                        new
                        {
                            Id = new Guid("87b57cba-7eb7-4182-82db-db8fffa720d5"),
                            Answers = "Tlen;Wodór;Azot;Hel",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Który pierwiastek ma symbol O?"
                        },
                        new
                        {
                            Id = new Guid("102b4dfa-2173-47c6-b298-f09bc7e38151"),
                            Answers = "Woda;Tlenek wodoru;Para wodna;Sól",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Co to jest H2O?"
                        },
                        new
                        {
                            Id = new Guid("0b0291e2-314c-47d9-96b8-fe26ca8affeb"),
                            Answers = "Jerzy Radziwiłowicz;Zbigniew Cybulski;Daniel Olbrychski;Andrzej Seweryn",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Kto zagrał główną rolę w filmie 'Człowiek z żelaza'?"
                        },
                        new
                        {
                            Id = new Guid("ea59804b-a4dd-4935-8db1-fa54f93d80c6"),
                            Answers = "Jerzy Antczak;Andrzej Wajda;Agnieszka Holland;Krzysztof Zanussi",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który polski reżyser stworzył film 'Noce i dnie'?"
                        },
                        new
                        {
                            Id = new Guid("c5f1386d-2af9-4417-9e00-90e1ae472683"),
                            Answers = "Adrien Brody;Roman Polański;Janusz Gajos;Bogusław Linda",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Który polski aktor zdobył Oscara za rolę w filmie 'Pianista'?"
                        },
                        new
                        {
                            Id = new Guid("775b35a9-5cb8-4c8b-a8fc-770cc71206c8"),
                            Answers = "Brazylia;Niemcy;Włochy;Argentyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Która drużyna zdobyła najwięcej tytułów Mistrza Świata w piłce nożnej?"
                        },
                        new
                        {
                            Id = new Guid("bd3ef533-75b8-4bfd-ae51-f8c168a52b93"),
                            Answers = "Lionel Messi;Cristiano Ronaldo;Johan Cruyff;Michel Platini",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Kto jest rekordzistą pod względem liczby zdobytych Złotych Piłek?"
                        },
                        new
                        {
                            Id = new Guid("b61b18d5-0aed-404b-8138-9665ac4a6c18"),
                            Answers = "PGE Narodowy;Stadion Śląski;Stadion Legii;Arena Gdańsk",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Jak nazywa się stadion narodowy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("96ea1b0e-2354-4465-b0f9-18b5e794dd10"),
                            Answers = "Karp;Dorsz;Halibut;Łosoś",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który gatunek ryb jest typowo uznawany za rybę słodkowodną?"
                        },
                        new
                        {
                            Id = new Guid("885f3d65-76a0-4bd8-afc4-f0f514067d57"),
                            Answers = "Kołowrotek;Wędzisko;Haczyk;Podbierak",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się urządzenie do nawijania żyłki?"
                        },
                        new
                        {
                            Id = new Guid("06670f83-1219-48c2-803f-641e515fbc2d"),
                            Answers = "Wędkarstwo gruntowe;Spinning;Trolling;Fly fishing",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Jak nazywa się metoda łowienia ryb z brzegu?"
                        },
                        new
                        {
                            Id = new Guid("e674c4b7-acff-4cab-8de9-dd7f9e3b7420"),
                            Answers = "Sejm;Senat;Trybunał Konstytucyjny;Rada Ministrów",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się główny organ ustawodawczy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("4d85f441-fc7e-4e32-80bf-cbd46ada8bb4"),
                            Answers = "Wielka Brytania;Francja;Niemcy;Włochy",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który kraj opuścił Unię Europejską w 2020 roku?"
                        },
                        new
                        {
                            Id = new Guid("fa239646-30f6-4f45-8571-a3d3e68f932c"),
                            Answers = "Konstytucja 3 maja;Konstytucja kwietniowa;Konstytucja marcowa;Konstytucja sierpniowa",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jak nazywa się polska konstytucja z 1791 roku?"
                        },
                        new
                        {
                            Id = new Guid("111374fb-85ee-41bf-bcc1-7d56b1f2ef28"),
                            Answers = "Kilimandżaro;Mount Kenya;Ruwenzori;Atlas",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się najwyższy szczyt Afryki?"
                        },
                        new
                        {
                            Id = new Guid("31327fdf-1a2c-4279-b314-687650061df0"),
                            Answers = "Morze Martwe;Morze Śródziemne;Morze Bałtyckie;Morze Kaspijskie",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Które morze jest nazywane najbardziej zasolonym?"
                        },
                        new
                        {
                            Id = new Guid("e09ba859-fefc-40b9-a48f-ba90ae7fae75"),
                            Answers = "Berlin;Monachium;Frankfurt;Hamburg",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jakie miasto jest stolicą Niemiec?"
                        },
                        new
                        {
                            Id = new Guid("bc03cb5c-c707-42e0-a942-c0568bb6ab56"),
                            Answers = "Jowisz;Saturn;Mars;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Która planeta Układu Słonecznego ma największą liczbę księżyców?"
                        },
                        new
                        {
                            Id = new Guid("c2800488-7586-448a-ae59-f1c2f4635001"),
                            Answers = "Eksplozja gwiazdy;Rodzaj galaktyki;Typ planety;Czarna dziura",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Co to jest supernowa?"
                        },
                        new
                        {
                            Id = new Guid("b17635d9-1ca2-4482-a350-c30154f00e0e"),
                            Answers = "Wenus;Jowisz;Mars;Syriusz",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Jak nazywa się drugi pod względem jasności obiekt na nocnym niebie po Księżycu?"
                        },
                        new
                        {
                            Id = new Guid("f9e9bf23-e456-4bca-b286-b8fe5ccedefa"),
                            Answers = "Gepard;Antylopa;Lew;Królik",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Które zwierzę jest najszybsze na lądzie?"
                        },
                        new
                        {
                            Id = new Guid("529c7c39-9c4a-469f-b774-ef9895a19141"),
                            Answers = "Metamorfoza;Adaptacja;Fotosynteza;Regeneracja",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się proces, w którym zwierzęta przechodzą zmiany w wyglądzie w czasie rozwoju?"
                        },
                        new
                        {
                            Id = new Guid("d1776b7f-d410-4a81-bb97-a065110ea1ad"),
                            Answers = "Komórki;Tkanki;Narządy;Organizmy",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Jakie są podstawowe jednostki budulcowe organizmów żywych?"
                        },
                        new
                        {
                            Id = new Guid("18013ff6-6375-44c5-b5df-2ed47c89484d"),
                            Answers = "Węgiel;Wapń;Cynk;Chrom",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Który pierwiastek ma symbol C?"
                        },
                        new
                        {
                            Id = new Guid("f2396016-d06c-4f27-88df-47773cf115d8"),
                            Answers = "Chlorek sodu;Wodorowęglan sodu;Siarczan sodu;Azotan sodu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który związek chemiczny jest głównym składnikiem soli kuchennej?"
                        },
                        new
                        {
                            Id = new Guid("aedc17e9-4084-4e90-a59c-96ebe54807eb"),
                            Answers = "Powietrze;Woda z piaskiem;Olej i woda;Puder do twarzy",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Która mieszanina jest jednorodna?"
                        },
                        new
                        {
                            Id = new Guid("159d444d-da6f-4641-809c-728e2389c30e"),
                            Answers = "Marek Piwowski;Andrzej Wajda;Roman Polański;Krzysztof Kieślowski",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Kto jest reżyserem filmu 'Rejs'?"
                        },
                        new
                        {
                            Id = new Guid("9645c32a-d902-4103-9a4a-665d1f5a3b01"),
                            Answers = "Olaf Lubaszenko;Bogusław Linda;Zbigniew Cybulski;Jan Nowicki",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Który polski aktor grał w filmie 'Krótki film o miłości'?"
                        },
                        new
                        {
                            Id = new Guid("68974a66-9be4-42fd-94d5-d3228372bc8c"),
                            Answers = "Człowiek z żelaza;Dekalog;Ida;Pokot",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Który film polskiego reżysera zdobył Złotą Palmę w Cannes?"
                        },
                        new
                        {
                            Id = new Guid("64166442-6cfe-499c-973a-9fdb597f38b7"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który polski piłkarz grał w Bayernie Monachium?"
                        },
                        new
                        {
                            Id = new Guid("6d176d58-3904-4ce3-af8b-1be4192d40f9"),
                            Answers = "Adam Nawałka;Jerzy Brzęczek;Paulo Sousa;Franciszek Smuda",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Kto był trenerem reprezentacji Polski w piłce nożnej na Euro 2016?"
                        },
                        new
                        {
                            Id = new Guid("8b659a31-6e44-4af4-aa8c-b6039dd786f7"),
                            Answers = "Ronaldo Nazário;Lionel Messi;Diego Maradona;Cristiano Ronaldo",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który piłkarz jest znany jako 'El Fenomeno'?"
                        },
                        new
                        {
                            Id = new Guid("39abd169-ac9d-44fe-8387-4c2e08323d4e"),
                            Answers = "Fly fishing;Trolling;Spinning;Wędkarstwo gruntowe",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Który rodzaj wędkowania wymaga sztucznej muchy?"
                        },
                        new
                        {
                            Id = new Guid("493a45b2-3541-472f-992f-9e965518f3d6"),
                            Answers = "Włókno węglowe;Drewno;Stal;Aluminium",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jakie jest najczęściej używane tworzywo do produkcji wędek?"
                        },
                        new
                        {
                            Id = new Guid("bdcc9258-1a0d-435e-9477-f812b1dc525c"),
                            Answers = "Ryba ciągnie przynętę;Ryba pływa obok;Wędka jest zanurzona;Przynęta jest zmieniana",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Co oznacza termin 'brać' w wędkarstwie?"
                        },
                        new
                        {
                            Id = new Guid("b6b7c0b0-59b0-40d2-ba61-291ff2b9e8b7"),
                            Answers = "Charles Michel;Ursula von der Leyen;Donald Tusk;Angela Merkel",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Kto jest przewodniczącym Rady Europejskiej w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("2157b58e-ee75-449a-829e-5d874bcfcff2"),
                            Answers = "Traktat Lizboński;Traktat z Maastricht;Traktat Rzymski;Traktat Amsterdamski",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który dokument jest podstawą prawną Unii Europejskiej?"
                        },
                        new
                        {
                            Id = new Guid("fefda9fa-f7e7-4342-a0b6-c1ac850cba67"),
                            Answers = "Mateusz Morawiecki;Donald Tusk;Jarosław Kaczyński;Beata Szydło",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się premier Polski w 2024 roku?"
                        });
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("GameQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            ConcurrencyStamp = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "98063297-e6e0-4b99-a132-1e79147ce720",
                            ConcurrencyStamp = "98063297-e6e0-4b99-a132-1e79147ce720",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithOne("GameParticipants")
                        .HasForeignKey("Awantura.Domain.Entities.GameParticipants", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithMany("PlayerScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Awantura.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameParticipants")
                        .IsRequired();

                    b.Navigation("PlayerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
