// <auto-generated />
using System;
using Awantura.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Awantura.Infrastructure.Migrations
{
    [DbContext(typeof(AwanturaAuthDbContext))]
    [Migration("20250101133113_Assign random Questions to the Game")]
    partial class AssignrandomQuestionstotheGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameState")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BluePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GreenPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YellowPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isBluePlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isGreenPlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isYellowPlayerReady")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("PlayerGameScores");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<int>("PointsForCorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adc14755-cbc6-466a-a022-eb4df7c9ad8c"),
                            Answers = "Warszawa;Kraków;Wrocław;Gdańsk",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Które miasto jest stolicą Polski?"
                        },
                        new
                        {
                            Id = new Guid("7e9bc7a9-a1e3-4e8f-a33f-0556d416263c"),
                            Answers = "Europa;Azja;Afryka;Ameryka Południowa",
                            Category = 0,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który kontynent jest największy pod względem powierzchni?"
                        },
                        new
                        {
                            Id = new Guid("fdee7b2f-6c01-414a-944c-455cb6f49ddc"),
                            Answers = "K2;Mont Blanc;Mount Everest;Kilimandżaro",
                            Category = 0,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się najwyższy szczyt na Ziemi?"
                        },
                        new
                        {
                            Id = new Guid("eabc6614-bfd1-45a3-b5de-6ad3b62f7b8b"),
                            Answers = "Saturn;Uran;Neptun;Jowisz",
                            Category = 1,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Która planeta w Układzie Słonecznym jest największa?"
                        },
                        new
                        {
                            Id = new Guid("e7f89301-5284-4f93-b013-8237b33f9b9d"),
                            Answers = "Droga Mleczna;Andromeda;Karłowata Galaktyka Strzelca;Wielka Mgławica",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się galaktyka, w której znajduje się Ziemia?"
                        },
                        new
                        {
                            Id = new Guid("d8f8238c-2252-4aaf-96b2-700d34efb4f7"),
                            Answers = "Wenus;Merkury;Mars;Ziemia",
                            Category = 1,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Która planeta jest najbliżej Słońca?"
                        },
                        new
                        {
                            Id = new Guid("cbad1a20-f060-4750-b4ab-8f260cbd4b32"),
                            Answers = "Oddychanie komórkowe;Fermentacja;Fotosynteza;Glukoneogeneza",
                            Category = 2,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Jak nazywa się proces, w którym rośliny przekształcają światło słoneczne w energię?"
                        },
                        new
                        {
                            Id = new Guid("1c74f6a4-2d93-4181-a20c-8c21d78e109e"),
                            Answers = "Wątroba;Płuca;Mózg;Serce",
                            Category = 2,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Który organ w ludzkim ciele odpowiada za pompowanie krwi?"
                        },
                        new
                        {
                            Id = new Guid("deeb3906-650a-4fb8-a860-e8362c478613"),
                            Answers = "Płetwal błękitny;Słoń;Rekin wielorybi;Żyrafa",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jakie zwierzę jest największe na świecie?"
                        },
                        new
                        {
                            Id = new Guid("e7bea4cf-7365-43b4-af33-3d2522f1b442"),
                            Answers = "Hel;Wodór;Azot;Tlen",
                            Category = 3,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Który pierwiastek ma symbol H?"
                        },
                        new
                        {
                            Id = new Guid("ad5ea88a-377e-4618-b3e6-15a4baa05783"),
                            Answers = "Kwas siarkowy;Kwas fosforowy;Kwas octowy;Kwas solny",
                            Category = 3,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Który kwas jest składnikiem octu?"
                        },
                        new
                        {
                            Id = new Guid("39a56df6-0898-4e81-9eb4-0a6a2a89ce4f"),
                            Answers = "Krzem;Cynk;Srebro;Węgiel",
                            Category = 3,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który pierwiastek jest podstawowym składnikiem diamentu?"
                        },
                        new
                        {
                            Id = new Guid("db3dafc5-b1d6-4e23-9538-476696457fa7"),
                            Answers = "Andrzej Wajda;Roman Polański;Krzysztof Kieślowski;Agnieszka Holland",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Kto jest reżyserem filmu 'Człowiek z marmuru'?"
                        },
                        new
                        {
                            Id = new Guid("ed85a576-c3ba-4259-8996-1258b2e77568"),
                            Answers = "Cicha noc;Ida;Katyń;Pan Tadeusz",
                            Category = 4,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który polski film zdobył Oscara?"
                        },
                        new
                        {
                            Id = new Guid("1a17ade2-4704-424d-8da4-b37d029c697f"),
                            Answers = "Andrzej Wajda;Agnieszka Holland;Krzysztof Kieślowski;Jerzy Hoffman",
                            Category = 4,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Kto jest twórcą trylogii filmowej 'Dekalog'?"
                        },
                        new
                        {
                            Id = new Guid("bb4fabad-7613-4cfe-a284-d5850f67885e"),
                            Answers = "Niemcy;Brazylia;Argentyna;Francja",
                            Category = 5,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Która reprezentacja wygrała Mistrzostwa Świata w Piłce Nożnej w 2018 roku?"
                        },
                        new
                        {
                            Id = new Guid("d4a09509-b109-44aa-98e0-317dca4a402f"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jak nazywa się polski piłkarz, który zdobył Złotą Piłkę?"
                        },
                        new
                        {
                            Id = new Guid("8868d947-4c0b-4973-a4bd-63d99460f09b"),
                            Answers = "FC Barcelona;Real Madryt;AC Milan;Bayern Monachium",
                            Category = 5,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który klub piłkarski wygrał najwięcej Lig Mistrzów?"
                        },
                        new
                        {
                            Id = new Guid("4b5dedf7-71b1-4a41-bf20-beb3fa1250ee"),
                            Answers = "Karaś;Leszcz;Pstrąg;Karp",
                            Category = 6,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Która ryba jest typowym drapieżnikiem?"
                        },
                        new
                        {
                            Id = new Guid("5e421707-6875-484f-91fa-f8560cfe7cd2"),
                            Answers = "Wędkarstwo gruntowe;Metoda odległościowa;Trolling;Spinning",
                            Category = 6,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Jak nazywa się metoda połowu na sztuczną przynętę?"
                        },
                        new
                        {
                            Id = new Guid("9b28ee3a-ee73-4997-b4ee-af689e58a995"),
                            Answers = "Waga wędkarska;Podbierak;Wędka;Kołowrotek",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Jak nazywa się przyrząd do ważenia złowionych ryb?"
                        },
                        new
                        {
                            Id = new Guid("cab8b151-512a-47db-a28e-e50531e0bddb"),
                            Answers = "Lech Wałęsa;Andrzej Duda;Aleksander Kwaśniewski;Donald Tusk",
                            Category = 7,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Kto jest prezydentem Polski w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("9f4a45ff-212c-4635-9a31-323eb9ec9b39"),
                            Answers = "Chiny;Indie;Stany Zjednoczone;Rosja",
                            Category = 7,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Które państwo posiada najwięcej miejsc w ONZ?"
                        },
                        new
                        {
                            Id = new Guid("ade5b3ce-b3e7-4588-9938-fb01d8d5231d"),
                            Answers = "Paryż;Berlin;Strasburg;Bruksela",
                            Category = 7,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się główna siedziba Parlamentu Europejskiego?"
                        },
                        new
                        {
                            Id = new Guid("1dd36b82-1a98-4d8d-8451-75a12ab80cfe"),
                            Answers = "Śniardwy;Mamry;Hańcza;Niegocin",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jakie jest największe jezioro w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("9c58bc1d-6b34-42ec-89c3-c4cf4201db12"),
                            Answers = "Niemcy;Czechy;Słowacja;Litwa",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który kraj graniczy z Polską na zachodzie?"
                        },
                        new
                        {
                            Id = new Guid("7650d763-b2cf-4a86-899c-9f2c6f54373d"),
                            Answers = "Tatry;Sudety;Karpaty;Bieszczady",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Które pasmo górskie znajduje się na południu Polski?"
                        },
                        new
                        {
                            Id = new Guid("b57d6a94-58eb-4097-b4bb-34072fa3aac5"),
                            Answers = "Merkury;Mars;Wenus;Pluton",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się najmniejsza planeta w Układzie Słonecznym?"
                        },
                        new
                        {
                            Id = new Guid("0db79961-5a82-44e6-9d8b-eff8c523df68"),
                            Answers = "Saturn;Jowisz;Neptun;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Która planeta jest znana z systemu pierścieni?"
                        },
                        new
                        {
                            Id = new Guid("6419c956-b787-43f1-b6dc-e528398a4528"),
                            Answers = "Księżyc;Mars;Wenus;Merkury",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się najbliższy Ziemi obiekt astronomiczny?"
                        },
                        new
                        {
                            Id = new Guid("c4f219ce-df18-4f22-acd4-5cb7cf69449d"),
                            Answers = "Lew;Tygrys;Słoń;Goryl",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jakie zwierzę jest nazywane królem dżungli?"
                        },
                        new
                        {
                            Id = new Guid("4c5acfdb-a595-4a00-b275-9b39bcb99185"),
                            Answers = "Botanika;Zoologia;Ekologia;Genetyka",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się nauka o roślinach?"
                        },
                        new
                        {
                            Id = new Guid("52487aa2-85fc-4f3e-a045-0c39b7409214"),
                            Answers = "Słuch;Wzrok;Dotyk;Smak",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który zmysł odpowiada za wykrywanie dźwięków?"
                        },
                        new
                        {
                            Id = new Guid("8afdc04f-ce16-45ce-8eb7-652113dd8dc5"),
                            Answers = "Au;Ag;Fe;Cu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się symbol chemiczny dla złota?"
                        },
                        new
                        {
                            Id = new Guid("3389428e-7914-4105-bf2f-90d1dedb3d3b"),
                            Answers = "Tlen;Wodór;Azot;Hel",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który pierwiastek ma symbol O?"
                        },
                        new
                        {
                            Id = new Guid("aef8cf0d-f8ce-4a5a-a263-6ec20d66ee43"),
                            Answers = "Woda;Tlenek wodoru;Para wodna;Sól",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Co to jest H2O?"
                        },
                        new
                        {
                            Id = new Guid("897a8d2d-5bf0-4760-8ebf-da24fc736ebe"),
                            Answers = "Jerzy Radziwiłowicz;Zbigniew Cybulski;Daniel Olbrychski;Andrzej Seweryn",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Kto zagrał główną rolę w filmie 'Człowiek z żelaza'?"
                        },
                        new
                        {
                            Id = new Guid("2dbe6145-2f37-4f99-8177-724753ba2bdc"),
                            Answers = "Jerzy Antczak;Andrzej Wajda;Agnieszka Holland;Krzysztof Zanussi",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Który polski reżyser stworzył film 'Noce i dnie'?"
                        },
                        new
                        {
                            Id = new Guid("3189040b-5f00-41e8-b858-b2c31fc67d53"),
                            Answers = "Adrien Brody;Roman Polański;Janusz Gajos;Bogusław Linda",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który polski aktor zdobył Oscara za rolę w filmie 'Pianista'?"
                        },
                        new
                        {
                            Id = new Guid("ae689f53-ce2a-485c-8185-23edf1f630d0"),
                            Answers = "Brazylia;Niemcy;Włochy;Argentyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Która drużyna zdobyła najwięcej tytułów Mistrza Świata w piłce nożnej?"
                        },
                        new
                        {
                            Id = new Guid("6a402556-357e-4833-b9d0-b4c6f9a80cd0"),
                            Answers = "Lionel Messi;Cristiano Ronaldo;Johan Cruyff;Michel Platini",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Kto jest rekordzistą pod względem liczby zdobytych Złotych Piłek?"
                        },
                        new
                        {
                            Id = new Guid("64cc86f9-0f83-4184-b096-134d2d7aca4e"),
                            Answers = "PGE Narodowy;Stadion Śląski;Stadion Legii;Arena Gdańsk",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się stadion narodowy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("7570af1f-2223-4c8d-860d-53433940e2b3"),
                            Answers = "Karp;Dorsz;Halibut;Łosoś",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Który gatunek ryb jest typowo uznawany za rybę słodkowodną?"
                        },
                        new
                        {
                            Id = new Guid("29227c74-489b-44e4-9c26-a966c066ff00"),
                            Answers = "Kołowrotek;Wędzisko;Haczyk;Podbierak",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się urządzenie do nawijania żyłki?"
                        },
                        new
                        {
                            Id = new Guid("95f88e83-94bf-48a0-873e-e471d51f6026"),
                            Answers = "Wędkarstwo gruntowe;Spinning;Trolling;Fly fishing",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jak nazywa się metoda łowienia ryb z brzegu?"
                        },
                        new
                        {
                            Id = new Guid("37fc84c8-6b2f-4e7b-b496-1aef7bef6d36"),
                            Answers = "Sejm;Senat;Trybunał Konstytucyjny;Rada Ministrów",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jak nazywa się główny organ ustawodawczy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("046099d3-ffec-40ad-9952-4f4341a524d7"),
                            Answers = "Wielka Brytania;Francja;Niemcy;Włochy",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który kraj opuścił Unię Europejską w 2020 roku?"
                        },
                        new
                        {
                            Id = new Guid("a170fcc0-68c8-4228-aa4e-786896cee872"),
                            Answers = "Konstytucja 3 maja;Konstytucja kwietniowa;Konstytucja marcowa;Konstytucja sierpniowa",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się polska konstytucja z 1791 roku?"
                        },
                        new
                        {
                            Id = new Guid("080fe37f-4ed8-44d5-9a2c-b9961c1c1d64"),
                            Answers = "Kilimandżaro;Mount Kenya;Ruwenzori;Atlas",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się najwyższy szczyt Afryki?"
                        },
                        new
                        {
                            Id = new Guid("ef23f33c-35d1-415b-bed3-61c8dd0a534c"),
                            Answers = "Morze Martwe;Morze Śródziemne;Morze Bałtyckie;Morze Kaspijskie",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Które morze jest nazywane najbardziej zasolonym?"
                        },
                        new
                        {
                            Id = new Guid("9a9971c0-9a1f-4559-8aa2-6efbc6e69fc0"),
                            Answers = "Berlin;Monachium;Frankfurt;Hamburg",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jakie miasto jest stolicą Niemiec?"
                        },
                        new
                        {
                            Id = new Guid("75836a23-3cfd-4b6d-8c5b-36a80c0d5fe2"),
                            Answers = "Jowisz;Saturn;Mars;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Która planeta Układu Słonecznego ma największą liczbę księżyców?"
                        },
                        new
                        {
                            Id = new Guid("38571509-4f2b-4c55-9b6a-c6416484c910"),
                            Answers = "Eksplozja gwiazdy;Rodzaj galaktyki;Typ planety;Czarna dziura",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Co to jest supernowa?"
                        },
                        new
                        {
                            Id = new Guid("7a4fc040-a248-47f1-8685-95b7fb552569"),
                            Answers = "Wenus;Jowisz;Mars;Syriusz",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jak nazywa się drugi pod względem jasności obiekt na nocnym niebie po Księżycu?"
                        },
                        new
                        {
                            Id = new Guid("1b8e330f-047a-42bd-8595-cf5ff8d357e3"),
                            Answers = "Gepard;Antylopa;Lew;Królik",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Które zwierzę jest najszybsze na lądzie?"
                        },
                        new
                        {
                            Id = new Guid("5e6ecba0-46d5-42b4-87d5-39e352ab1616"),
                            Answers = "Metamorfoza;Adaptacja;Fotosynteza;Regeneracja",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się proces, w którym zwierzęta przechodzą zmiany w wyglądzie w czasie rozwoju?"
                        },
                        new
                        {
                            Id = new Guid("83b9ae0a-747f-4863-be87-4ae9598a62b6"),
                            Answers = "Komórki;Tkanki;Narządy;Organizmy",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Jakie są podstawowe jednostki budulcowe organizmów żywych?"
                        },
                        new
                        {
                            Id = new Guid("6982c845-d49c-4d02-9fe9-97bbd930f762"),
                            Answers = "Węgiel;Wapń;Cynk;Chrom",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Który pierwiastek ma symbol C?"
                        },
                        new
                        {
                            Id = new Guid("a0ae75be-1029-47f0-bf60-5c913e4455cb"),
                            Answers = "Chlorek sodu;Wodorowęglan sodu;Siarczan sodu;Azotan sodu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który związek chemiczny jest głównym składnikiem soli kuchennej?"
                        },
                        new
                        {
                            Id = new Guid("fd6b311e-a37f-4bb3-8d4b-4882f8690a5c"),
                            Answers = "Powietrze;Woda z piaskiem;Olej i woda;Puder do twarzy",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Która mieszanina jest jednorodna?"
                        },
                        new
                        {
                            Id = new Guid("0ca2315d-7432-4067-ac8c-10b5b3f69baa"),
                            Answers = "Marek Piwowski;Andrzej Wajda;Roman Polański;Krzysztof Kieślowski",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Kto jest reżyserem filmu 'Rejs'?"
                        },
                        new
                        {
                            Id = new Guid("d281aecd-2b3e-455c-959e-99d74a223833"),
                            Answers = "Olaf Lubaszenko;Bogusław Linda;Zbigniew Cybulski;Jan Nowicki",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który polski aktor grał w filmie 'Krótki film o miłości'?"
                        },
                        new
                        {
                            Id = new Guid("c46c2281-8a37-4e90-8e4f-8d7147522a49"),
                            Answers = "Człowiek z żelaza;Dekalog;Ida;Pokot",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Który film polskiego reżysera zdobył Złotą Palmę w Cannes?"
                        },
                        new
                        {
                            Id = new Guid("9d8ec2bb-9e28-4fb1-a7eb-200638792f61"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który polski piłkarz grał w Bayernie Monachium?"
                        },
                        new
                        {
                            Id = new Guid("c06e23d3-eeb2-42b7-a395-9a9c0261ee76"),
                            Answers = "Adam Nawałka;Jerzy Brzęczek;Paulo Sousa;Franciszek Smuda",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Kto był trenerem reprezentacji Polski w piłce nożnej na Euro 2016?"
                        },
                        new
                        {
                            Id = new Guid("b0a5828a-a443-43ed-b0e0-6896858a52c8"),
                            Answers = "Ronaldo Nazário;Lionel Messi;Diego Maradona;Cristiano Ronaldo",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który piłkarz jest znany jako 'El Fenomeno'?"
                        },
                        new
                        {
                            Id = new Guid("9e2fd0df-a568-4596-97aa-b9c0ffa45209"),
                            Answers = "Fly fishing;Trolling;Spinning;Wędkarstwo gruntowe",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który rodzaj wędkowania wymaga sztucznej muchy?"
                        },
                        new
                        {
                            Id = new Guid("caf28a6d-5572-4128-b174-f6213c612270"),
                            Answers = "Włókno węglowe;Drewno;Stal;Aluminium",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Jakie jest najczęściej używane tworzywo do produkcji wędek?"
                        },
                        new
                        {
                            Id = new Guid("80e3f59a-daa8-4715-bc5a-99479b8fd766"),
                            Answers = "Ryba ciągnie przynętę;Ryba pływa obok;Wędka jest zanurzona;Przynęta jest zmieniana",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Co oznacza termin 'brać' w wędkarstwie?"
                        },
                        new
                        {
                            Id = new Guid("8a0bb504-282e-4434-b11c-d68df08bec06"),
                            Answers = "Charles Michel;Ursula von der Leyen;Donald Tusk;Angela Merkel",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Kto jest przewodniczącym Rady Europejskiej w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("0e8e0920-3ff6-4734-b517-5b6f31f07f7b"),
                            Answers = "Traktat Lizboński;Traktat z Maastricht;Traktat Rzymski;Traktat Amsterdamski",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który dokument jest podstawą prawną Unii Europejskiej?"
                        },
                        new
                        {
                            Id = new Guid("c343980a-da1c-412d-8603-18a4fde6c411"),
                            Answers = "Mateusz Morawiecki;Donald Tusk;Jarosław Kaczyński;Beata Szydło",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Jak nazywa się premier Polski w 2024 roku?"
                        });
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("GameQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            ConcurrencyStamp = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "98063297-e6e0-4b99-a132-1e79147ce720",
                            ConcurrencyStamp = "98063297-e6e0-4b99-a132-1e79147ce720",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithOne("GameParticipants")
                        .HasForeignKey("Awantura.Domain.Entities.GameParticipants", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithMany("PlayerScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Awantura.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameParticipants")
                        .IsRequired();

                    b.Navigation("PlayerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
