// <auto-generated />
using System;
using Awantura.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Awantura.Infrastructure.Migrations
{
    [DbContext(typeof(AwanturaAuthDbContext))]
    [Migration("20250105105747_Add Bids table")]
    partial class AddBidstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Awantura.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId", "TimeStamp");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GameState")
                        .HasColumnType("int");

                    b.Property<int>("Pool")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BluePlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GreenPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YellowPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isBluePlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isGreenPlayerReady")
                        .HasColumnType("bit");

                    b.Property<bool>("isYellowPlayerReady")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameParticipants");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("PlayerGameScores");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<int>("PointsForCorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2714ecbd-fe11-44fa-9f27-c6bf22843187"),
                            Answers = "Warszawa;Kraków;Wrocław;Gdańsk",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Które miasto jest stolicą Polski?"
                        },
                        new
                        {
                            Id = new Guid("3a8d148c-ef6d-4669-a7e8-3e157c3ad1b0"),
                            Answers = "Europa;Azja;Afryka;Ameryka Południowa",
                            Category = 0,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który kontynent jest największy pod względem powierzchni?"
                        },
                        new
                        {
                            Id = new Guid("6084bb1b-4577-499f-b914-6ced0458a577"),
                            Answers = "K2;Mont Blanc;Mount Everest;Kilimandżaro",
                            Category = 0,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się najwyższy szczyt na Ziemi?"
                        },
                        new
                        {
                            Id = new Guid("132629af-95e5-4384-88f9-17f018c06813"),
                            Answers = "Saturn;Uran;Neptun;Jowisz",
                            Category = 1,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Która planeta w Układzie Słonecznym jest największa?"
                        },
                        new
                        {
                            Id = new Guid("5294aba1-9aef-48bd-8355-e0686557adec"),
                            Answers = "Droga Mleczna;Andromeda;Karłowata Galaktyka Strzelca;Wielka Mgławica",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Jak nazywa się galaktyka, w której znajduje się Ziemia?"
                        },
                        new
                        {
                            Id = new Guid("a220dbcf-da5d-4f7d-a45b-193af9f2bb35"),
                            Answers = "Wenus;Merkury;Mars;Ziemia",
                            Category = 1,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Która planeta jest najbliżej Słońca?"
                        },
                        new
                        {
                            Id = new Guid("41313dcf-9347-4471-b0c2-f49cc0763ccf"),
                            Answers = "Oddychanie komórkowe;Fermentacja;Fotosynteza;Glukoneogeneza",
                            Category = 2,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jak nazywa się proces, w którym rośliny przekształcają światło słoneczne w energię?"
                        },
                        new
                        {
                            Id = new Guid("9eae57f1-b0c3-453c-967a-99223af90aa5"),
                            Answers = "Wątroba;Płuca;Mózg;Serce",
                            Category = 2,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który organ w ludzkim ciele odpowiada za pompowanie krwi?"
                        },
                        new
                        {
                            Id = new Guid("868b8b35-aa5f-43d5-a012-a0d41a984e3f"),
                            Answers = "Płetwal błękitny;Słoń;Rekin wielorybi;Żyrafa",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Jakie zwierzę jest największe na świecie?"
                        },
                        new
                        {
                            Id = new Guid("5de74778-1a68-4bcc-bb05-212234eabf81"),
                            Answers = "Hel;Wodór;Azot;Tlen",
                            Category = 3,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Który pierwiastek ma symbol H?"
                        },
                        new
                        {
                            Id = new Guid("3df41ba4-2db2-446f-847f-33fbbceb85a1"),
                            Answers = "Kwas siarkowy;Kwas fosforowy;Kwas octowy;Kwas solny",
                            Category = 3,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Który kwas jest składnikiem octu?"
                        },
                        new
                        {
                            Id = new Guid("9aecab73-10b7-40b2-ba7c-1dab497a2be8"),
                            Answers = "Krzem;Cynk;Srebro;Węgiel",
                            Category = 3,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który pierwiastek jest podstawowym składnikiem diamentu?"
                        },
                        new
                        {
                            Id = new Guid("c6ed369a-7515-4bfc-ace9-929b1e2bc37a"),
                            Answers = "Andrzej Wajda;Roman Polański;Krzysztof Kieślowski;Agnieszka Holland",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Kto jest reżyserem filmu 'Człowiek z marmuru'?"
                        },
                        new
                        {
                            Id = new Guid("6d719ee9-3908-4199-8f24-f29d22f3eae7"),
                            Answers = "Cicha noc;Ida;Katyń;Pan Tadeusz",
                            Category = 4,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Który polski film zdobył Oscara?"
                        },
                        new
                        {
                            Id = new Guid("4c025423-156a-4a87-b2ac-b0c5bf0196ee"),
                            Answers = "Andrzej Wajda;Agnieszka Holland;Krzysztof Kieślowski;Jerzy Hoffman",
                            Category = 4,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Kto jest twórcą trylogii filmowej 'Dekalog'?"
                        },
                        new
                        {
                            Id = new Guid("0918d92a-150a-4dbd-b4f7-24f734694613"),
                            Answers = "Niemcy;Brazylia;Argentyna;Francja",
                            Category = 5,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Która reprezentacja wygrała Mistrzostwa Świata w Piłce Nożnej w 2018 roku?"
                        },
                        new
                        {
                            Id = new Guid("1f65ac8f-c312-4636-a953-924f93010da5"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się polski piłkarz, który zdobył Złotą Piłkę?"
                        },
                        new
                        {
                            Id = new Guid("81f871cd-e74f-4c87-b268-e9cb7d84c8fb"),
                            Answers = "FC Barcelona;Real Madryt;AC Milan;Bayern Monachium",
                            Category = 5,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który klub piłkarski wygrał najwięcej Lig Mistrzów?"
                        },
                        new
                        {
                            Id = new Guid("830140d9-8634-4a00-a454-9b4291eb8a84"),
                            Answers = "Karaś;Leszcz;Pstrąg;Karp",
                            Category = 6,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Która ryba jest typowym drapieżnikiem?"
                        },
                        new
                        {
                            Id = new Guid("2d237350-3595-4a9b-a0d2-d29ba6afa01c"),
                            Answers = "Wędkarstwo gruntowe;Metoda odległościowa;Trolling;Spinning",
                            Category = 6,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Jak nazywa się metoda połowu na sztuczną przynętę?"
                        },
                        new
                        {
                            Id = new Guid("caeab67f-540b-451f-8337-3cd7b8c727ce"),
                            Answers = "Waga wędkarska;Podbierak;Wędka;Kołowrotek",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się przyrząd do ważenia złowionych ryb?"
                        },
                        new
                        {
                            Id = new Guid("62592de9-32fc-4fa5-8650-4f0b621c6517"),
                            Answers = "Lech Wałęsa;Andrzej Duda;Aleksander Kwaśniewski;Donald Tusk",
                            Category = 7,
                            CorrectAnswer = 1,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Kto jest prezydentem Polski w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("b9c6f9d8-857a-48f7-bb45-0288f32e7c8f"),
                            Answers = "Chiny;Indie;Stany Zjednoczone;Rosja",
                            Category = 7,
                            CorrectAnswer = 2,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Które państwo posiada najwięcej miejsc w ONZ?"
                        },
                        new
                        {
                            Id = new Guid("f55312e9-4f56-472c-b0bf-e6c1774bcfb7"),
                            Answers = "Paryż;Berlin;Strasburg;Bruksela",
                            Category = 7,
                            CorrectAnswer = 3,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się główna siedziba Parlamentu Europejskiego?"
                        },
                        new
                        {
                            Id = new Guid("1979a748-3324-4449-bead-41756e5645d3"),
                            Answers = "Śniardwy;Mamry;Hańcza;Niegocin",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jakie jest największe jezioro w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("aedb214f-a2e6-4dda-b80b-26a6b6b1505e"),
                            Answers = "Niemcy;Czechy;Słowacja;Litwa",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który kraj graniczy z Polską na zachodzie?"
                        },
                        new
                        {
                            Id = new Guid("54735673-4e55-451f-b4c1-00d9aef7178c"),
                            Answers = "Tatry;Sudety;Karpaty;Bieszczady",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Które pasmo górskie znajduje się na południu Polski?"
                        },
                        new
                        {
                            Id = new Guid("67be4211-880a-43f7-a34b-41cfbfe8bb48"),
                            Answers = "Merkury;Mars;Wenus;Pluton",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Jak nazywa się najmniejsza planeta w Układzie Słonecznym?"
                        },
                        new
                        {
                            Id = new Guid("c956cb7f-f2d4-4728-9757-f5cd6cc63578"),
                            Answers = "Saturn;Jowisz;Neptun;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Która planeta jest znana z systemu pierścieni?"
                        },
                        new
                        {
                            Id = new Guid("e4a31fb8-055f-44a3-ba86-d23ed94f3631"),
                            Answers = "Księżyc;Mars;Wenus;Merkury",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jak nazywa się najbliższy Ziemi obiekt astronomiczny?"
                        },
                        new
                        {
                            Id = new Guid("97053a0f-54d1-4fbf-b858-198988c4f68b"),
                            Answers = "Lew;Tygrys;Słoń;Goryl",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Jakie zwierzę jest nazywane królem dżungli?"
                        },
                        new
                        {
                            Id = new Guid("a187cd2b-5f83-4587-aae2-87c1fcb159db"),
                            Answers = "Botanika;Zoologia;Ekologia;Genetyka",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 7,
                            QuestionText = "Jak nazywa się nauka o roślinach?"
                        },
                        new
                        {
                            Id = new Guid("fb2ece36-4c98-4ea8-9bee-86c4b91de629"),
                            Answers = "Słuch;Wzrok;Dotyk;Smak",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który zmysł odpowiada za wykrywanie dźwięków?"
                        },
                        new
                        {
                            Id = new Guid("5a698253-93f7-499c-9a33-2a9bc2e929c9"),
                            Answers = "Au;Ag;Fe;Cu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jak nazywa się symbol chemiczny dla złota?"
                        },
                        new
                        {
                            Id = new Guid("4fb34909-5284-48a3-85f6-2c1417a37235"),
                            Answers = "Tlen;Wodór;Azot;Hel",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Który pierwiastek ma symbol O?"
                        },
                        new
                        {
                            Id = new Guid("1144ed99-7efa-4f44-a6cb-ae08fc287f4f"),
                            Answers = "Woda;Tlenek wodoru;Para wodna;Sól",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Co to jest H2O?"
                        },
                        new
                        {
                            Id = new Guid("f9b7d78f-b8c6-4604-ad68-61f11bdef51a"),
                            Answers = "Jerzy Radziwiłowicz;Zbigniew Cybulski;Daniel Olbrychski;Andrzej Seweryn",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Kto zagrał główną rolę w filmie 'Człowiek z żelaza'?"
                        },
                        new
                        {
                            Id = new Guid("583bbe89-6251-4c9d-80ee-6b6f04c5361c"),
                            Answers = "Jerzy Antczak;Andrzej Wajda;Agnieszka Holland;Krzysztof Zanussi",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Który polski reżyser stworzył film 'Noce i dnie'?"
                        },
                        new
                        {
                            Id = new Guid("5991ef0f-5cf3-485b-8897-a6acae9a31e1"),
                            Answers = "Adrien Brody;Roman Polański;Janusz Gajos;Bogusław Linda",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Który polski aktor zdobył Oscara za rolę w filmie 'Pianista'?"
                        },
                        new
                        {
                            Id = new Guid("3140eb5f-96e2-4599-be66-ee1226aea7f3"),
                            Answers = "Brazylia;Niemcy;Włochy;Argentyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Która drużyna zdobyła najwięcej tytułów Mistrza Świata w piłce nożnej?"
                        },
                        new
                        {
                            Id = new Guid("e2a6b191-2bdf-41df-b7fe-1eb956b51468"),
                            Answers = "Lionel Messi;Cristiano Ronaldo;Johan Cruyff;Michel Platini",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Kto jest rekordzistą pod względem liczby zdobytych Złotych Piłek?"
                        },
                        new
                        {
                            Id = new Guid("8e88c57c-f913-4fce-9ae2-6b33019b873f"),
                            Answers = "PGE Narodowy;Stadion Śląski;Stadion Legii;Arena Gdańsk",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Jak nazywa się stadion narodowy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("44257b14-c175-432c-9fc2-4435f425c344"),
                            Answers = "Karp;Dorsz;Halibut;Łosoś",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Który gatunek ryb jest typowo uznawany za rybę słodkowodną?"
                        },
                        new
                        {
                            Id = new Guid("45d888cf-a141-4c38-8e4e-c620cf34ce0a"),
                            Answers = "Kołowrotek;Wędzisko;Haczyk;Podbierak",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się urządzenie do nawijania żyłki?"
                        },
                        new
                        {
                            Id = new Guid("10b2c5bc-1845-4bf7-b384-71ae9a397c4c"),
                            Answers = "Wędkarstwo gruntowe;Spinning;Trolling;Fly fishing",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Jak nazywa się metoda łowienia ryb z brzegu?"
                        },
                        new
                        {
                            Id = new Guid("b20d901a-b5db-48a1-9655-cca73177d87e"),
                            Answers = "Sejm;Senat;Trybunał Konstytucyjny;Rada Ministrów",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jak nazywa się główny organ ustawodawczy w Polsce?"
                        },
                        new
                        {
                            Id = new Guid("ece14492-0230-4c52-80d8-7cc4e1798b58"),
                            Answers = "Wielka Brytania;Francja;Niemcy;Włochy",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Który kraj opuścił Unię Europejską w 2020 roku?"
                        },
                        new
                        {
                            Id = new Guid("6e4466ab-b478-47ea-8137-fafe0151623e"),
                            Answers = "Konstytucja 3 maja;Konstytucja kwietniowa;Konstytucja marcowa;Konstytucja sierpniowa",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jak nazywa się polska konstytucja z 1791 roku?"
                        },
                        new
                        {
                            Id = new Guid("26509470-c130-437c-a013-cb6b2148356b"),
                            Answers = "Kilimandżaro;Mount Kenya;Ruwenzori;Atlas",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 5,
                            QuestionText = "Jak nazywa się najwyższy szczyt Afryki?"
                        },
                        new
                        {
                            Id = new Guid("7d0e41ed-faf9-4052-b313-3f9402d0862e"),
                            Answers = "Morze Martwe;Morze Śródziemne;Morze Bałtyckie;Morze Kaspijskie",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 8,
                            QuestionText = "Które morze jest nazywane najbardziej zasolonym?"
                        },
                        new
                        {
                            Id = new Guid("1f04a98d-09f0-4e4c-a90f-9085355af062"),
                            Answers = "Berlin;Monachium;Frankfurt;Hamburg",
                            Category = 0,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Jakie miasto jest stolicą Niemiec?"
                        },
                        new
                        {
                            Id = new Guid("af595afa-002c-4573-a67f-78103d63f4e1"),
                            Answers = "Jowisz;Saturn;Mars;Uran",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Która planeta Układu Słonecznego ma największą liczbę księżyców?"
                        },
                        new
                        {
                            Id = new Guid("a80d33d5-4477-4d48-86f0-2836ce19708e"),
                            Answers = "Eksplozja gwiazdy;Rodzaj galaktyki;Typ planety;Czarna dziura",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 18,
                            QuestionText = "Co to jest supernowa?"
                        },
                        new
                        {
                            Id = new Guid("2e2d7d04-2cad-4461-8dd0-81fdf0d83366"),
                            Answers = "Wenus;Jowisz;Mars;Syriusz",
                            Category = 1,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 11,
                            QuestionText = "Jak nazywa się drugi pod względem jasności obiekt na nocnym niebie po Księżycu?"
                        },
                        new
                        {
                            Id = new Guid("2f9fa534-884e-40f7-b9fc-fe4af501c221"),
                            Answers = "Gepard;Antylopa;Lew;Królik",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Które zwierzę jest najszybsze na lądzie?"
                        },
                        new
                        {
                            Id = new Guid("db3e8fb1-9a5b-4d8f-b62e-30f96e33fec3"),
                            Answers = "Metamorfoza;Adaptacja;Fotosynteza;Regeneracja",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 9,
                            QuestionText = "Jak nazywa się proces, w którym zwierzęta przechodzą zmiany w wyglądzie w czasie rozwoju?"
                        },
                        new
                        {
                            Id = new Guid("91207999-6c34-4970-a90e-3192a004bde9"),
                            Answers = "Komórki;Tkanki;Narządy;Organizmy",
                            Category = 2,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Jakie są podstawowe jednostki budulcowe organizmów żywych?"
                        },
                        new
                        {
                            Id = new Guid("f644f55d-da5b-4630-a469-74ce0d6606c2"),
                            Answers = "Węgiel;Wapń;Cynk;Chrom",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który pierwiastek ma symbol C?"
                        },
                        new
                        {
                            Id = new Guid("755fd8f3-81fe-474c-a4da-cf150fa0ec64"),
                            Answers = "Chlorek sodu;Wodorowęglan sodu;Siarczan sodu;Azotan sodu",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Który związek chemiczny jest głównym składnikiem soli kuchennej?"
                        },
                        new
                        {
                            Id = new Guid("17d35499-0f7f-48e5-9aac-f9be0b52c5b3"),
                            Answers = "Powietrze;Woda z piaskiem;Olej i woda;Puder do twarzy",
                            Category = 3,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 13,
                            QuestionText = "Która mieszanina jest jednorodna?"
                        },
                        new
                        {
                            Id = new Guid("8aab8195-aad8-4500-b34f-ccceec595e3c"),
                            Answers = "Marek Piwowski;Andrzej Wajda;Roman Polański;Krzysztof Kieślowski",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Kto jest reżyserem filmu 'Rejs'?"
                        },
                        new
                        {
                            Id = new Guid("e50e5119-ab8b-4519-aa5c-b85a3b5de822"),
                            Answers = "Olaf Lubaszenko;Bogusław Linda;Zbigniew Cybulski;Jan Nowicki",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Który polski aktor grał w filmie 'Krótki film o miłości'?"
                        },
                        new
                        {
                            Id = new Guid("434cf6dc-03a0-42ff-8669-30dfe1d1d54c"),
                            Answers = "Człowiek z żelaza;Dekalog;Ida;Pokot",
                            Category = 4,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 15,
                            QuestionText = "Który film polskiego reżysera zdobył Złotą Palmę w Cannes?"
                        },
                        new
                        {
                            Id = new Guid("7f89beef-91dd-46e5-9fb7-b35bb8fccd9a"),
                            Answers = "Robert Lewandowski;Zbigniew Boniek;Grzegorz Lato;Kazimierz Deyna",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 16,
                            QuestionText = "Który polski piłkarz grał w Bayernie Monachium?"
                        },
                        new
                        {
                            Id = new Guid("d0f362ad-2e49-4d92-ba1b-fda6fdc7c307"),
                            Answers = "Adam Nawałka;Jerzy Brzęczek;Paulo Sousa;Franciszek Smuda",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 12,
                            QuestionText = "Kto był trenerem reprezentacji Polski w piłce nożnej na Euro 2016?"
                        },
                        new
                        {
                            Id = new Guid("1534e5c9-0780-4122-b3f4-ee20b0e335fc"),
                            Answers = "Ronaldo Nazário;Lionel Messi;Diego Maradona;Cristiano Ronaldo",
                            Category = 5,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Który piłkarz jest znany jako 'El Fenomeno'?"
                        },
                        new
                        {
                            Id = new Guid("99f014c8-1ba4-4477-b445-41a29e66d85f"),
                            Answers = "Fly fishing;Trolling;Spinning;Wędkarstwo gruntowe",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 10,
                            QuestionText = "Który rodzaj wędkowania wymaga sztucznej muchy?"
                        },
                        new
                        {
                            Id = new Guid("7a32a46b-e774-4980-8edd-511ef644da50"),
                            Answers = "Włókno węglowe;Drewno;Stal;Aluminium",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 20,
                            QuestionText = "Jakie jest najczęściej używane tworzywo do produkcji wędek?"
                        },
                        new
                        {
                            Id = new Guid("deb2d6e4-6e5d-4b37-a946-c9a55523bdea"),
                            Answers = "Ryba ciągnie przynętę;Ryba pływa obok;Wędka jest zanurzona;Przynęta jest zmieniana",
                            Category = 6,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 17,
                            QuestionText = "Co oznacza termin 'brać' w wędkarstwie?"
                        },
                        new
                        {
                            Id = new Guid("0ab0644c-6d21-43f5-80a1-483414115149"),
                            Answers = "Charles Michel;Ursula von der Leyen;Donald Tusk;Angela Merkel",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 19,
                            QuestionText = "Kto jest przewodniczącym Rady Europejskiej w 2024 roku?"
                        },
                        new
                        {
                            Id = new Guid("b9c02efa-d05e-4d6c-8e8f-25434d66ecb0"),
                            Answers = "Traktat Lizboński;Traktat z Maastricht;Traktat Rzymski;Traktat Amsterdamski",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 14,
                            QuestionText = "Który dokument jest podstawą prawną Unii Europejskiej?"
                        },
                        new
                        {
                            Id = new Guid("fe31e20f-4a0f-4140-8eae-3f377c417866"),
                            Answers = "Mateusz Morawiecki;Donald Tusk;Jarosław Kaczyński;Beata Szydło",
                            Category = 7,
                            CorrectAnswer = 0,
                            PointsForCorrectAnswer = 6,
                            QuestionText = "Jak nazywa się premier Polski w 2024 roku?"
                        });
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("GameQuestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            ConcurrencyStamp = "a4525c03-1ae5-4b69-b79a-3948bdc5f147",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "98063297-e6e0-4b99-a132-1e79147ce720",
                            ConcurrencyStamp = "98063297-e6e0-4b99-a132-1e79147ce720",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Bid", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Awantura.Domain.Entities.GameParticipants", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithOne("GameParticipants")
                        .HasForeignKey("Awantura.Domain.Entities.GameParticipants", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Awantura.Domain.Entities.PlayerGameScore", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", "Game")
                        .WithMany("PlayerScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameQuestion", b =>
                {
                    b.HasOne("Awantura.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Awantura.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Awantura.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameParticipants")
                        .IsRequired();

                    b.Navigation("PlayerScores");
                });
#pragma warning restore 612, 618
        }
    }
}
